server:
  port: 8887
spring:
  application:
    name: CONFIG-CLIENT
  cloud:
    consul:
      host: localhost
      port: 8500
  rabbitmq:
    host: 192.168.204.130
    port: 5672
    username: admin
    password: 111111

